In [3]:
import numpy as np
import pandas as pd

In [4]:
df = pd.read_csv("/content/train.csv")

In [5]:
df.head()

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

In [6]:
df = df.fillna(df.median())

In [7]:
X = df.iloc[:,1:]
y = df.iloc[:,0]

In [8]:
X.isnull().sum()

pixel0      0
pixel1      0
pixel2      0
pixel3      0
pixel4      0
           ..
pixel779    0
pixel780    0
pixel781    0
pixel782    0
pixel783    0
Length: 784, dtype: int64

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [11]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [12]:
lr = LogisticRegression()
dc = DecisionTreeClassifier()

In [13]:
lr.fit(X_train,y_train)
dc.fit(X_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


DecisionTreeClassifier()

In [14]:
y_pred1 = lr.predict(X_test)
y_pred2 = dc.predict(X_test)

In [15]:
from sklearn.metrics import accuracy_score,confusion_matrix
print("Accuracy of Logistic Regression",accuracy_score(y_test,y_pred1))
print("Accuracy of Decision Trees",accuracy_score(y_test,y_pred2))

Accuracy of Logistic Regression 0.9145238095238095
Accuracy of Decision Trees 0.8513095238095238


In [16]:
print("Logistic Regression Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred1),columns=list(range(0,10)))

Logistic Regression Confusion Matrix



0    1    2    3    4    5    6    7    8    9
0  791    0    1    0    1    9   11    1    6    1
1    0  938    2    4    0    3    0    3   12    0
2    2    9  745   16    9    4   13   13   15    3
3    1    4   19  763    0   36    5    5   20   11
4    2    5    4    0  804    1    7    3    9   21
5    9    3    4   23   10  610   15   10   34   11
6   12    4   12    1    7    8  789    0    5    1
7    3    2   13    6    4    2    0  812    2   29
8   11   12   13   18    1   21    6    6  694   11
9    3    6    2   14   25    4    0   37    7  736

In [17]:
from sklearn.metrics import precision_score, recall_score,f1_score

In [18]:
precision_score(y_test,y_pred1,average=None)

array([0.94844125, 0.95422177, 0.91411043, 0.90295858, 0.93379791,
       0.8739255 , 0.93262411, 0.91235955, 0.86318408, 0.89320388])

In [19]:
recall_score(y_test,y_pred1,average=None)

array([0.9634592 , 0.97505198, 0.8986731 , 0.88310185, 0.93925234,
       0.83676269, 0.94040524, 0.930126  , 0.87515763, 0.882494  ])

In [20]:
f1_score(y_test,y_pred1,average=None)

array([0.95589124, 0.96452442, 0.90632603, 0.89291984, 0.93651718,
       0.85494043, 0.93649852, 0.92115712, 0.86912962, 0.88781665])

In [24]:
precision_score(y_test,y_pred1,average='macro')

0.9128827064397905

In [23]:
recall_score(y_test,y_pred1,average='macro')

0.9124484028871509

In [22]:
f1_score(y_test,y_pred1,average='macro')

0.9125721045561427

In [25]:
precision_score(y_test,y_pred1,average='weighted')

0.9142150713630827

In [26]:
from sklearn.metrics import classification_report

In [27]:
print(classification_report(y_test,y_pred1))

              precision    recall  f1-score   support

           0       0.95      0.96      0.96       821
           1       0.95      0.98      0.96       962
           2       0.91      0.90      0.91       829
           3       0.90      0.88      0.89       864
           4       0.93      0.94      0.94       856
           5       0.87      0.84      0.85       729
           6       0.93      0.94      0.94       839
           7       0.91      0.93      0.92       873
           8       0.86      0.88      0.87       793
           9       0.89      0.88      0.89       834

    accuracy                           0.91      8400
   macro avg       0.91      0.91      0.91      8400
weighted avg       0.91      0.91      0.91      8400

